feat: Python test and release workflows

diff --git a/.github/workflows/release-python.yml b/.github/workflows/release-python.yml
--- a/.github/workflows/release-python.yml
+++ b/.github/workflows/release-python.yml
@@ -1,6 +1,13 @@
 name: Python Release
 
 on:
+  push:
+    tags:
+      - 'python/[0-9]+.[0-9]+.[0-9]+'
+      - 'python/[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
+      - 'python/[0-9]+.[0-9]+.[0-9]+-beta[0-9]+'
+      - 'python/[0-9]+.[0-9]+.[0-9]+-alpha[0-9]+'
+
   workflow_dispatch:
     inputs:
       create_test_release:
@@ -8,101 +15,134 @@ on:
         required: false
         type: boolean
         default: true
-#  push:
-#    tags:
-#      - '[0-9]+.[0-9]+.[0-9]*'
-jobs:
 
-  build:
-    runs-on: ${{matrix.os}}
-    strategy:
-      matrix:
-        os: [windows-latest,macos-latest,ubuntu-latest] #, windows-latest, macos-latest, macos-14, ubuntu-latest,
-        python: [38,39,310,311,312]
+      create_release:
+        description: 'Create a PyPi release'
+        required: false
+        type: boolean
+        default: false
+
+jobs:
+  py-test:
+    name: Lint and Test Python Binding
+    uses: ./.github/workflows/python-test.yml
+
+  tag-job:
+    needs: [ py-test ]
+    runs-on: ubuntu-latest
+    name: Get Tag
+    outputs:
+      tag: ${{ steps.tag-output.outputs.tag }}
+      release-tag: ${{ steps.tag-output.outputs.release-tag }}
     steps:
-      - name: Dependencies
-        if: matrix.os == 'ubuntu-latest'
-        id: depends
+      - name: Get Tag From Ref
+        id: tag-ref
+        if: github.event_name == 'push'
+        shell: bash
         run: |
-          sudo apt-get update
-          sudo apt-get install build-essential libcurl4-openssl-dev
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v2
-        if: matrix.os == 'ubuntu-latest'
-      - uses: actions/checkout@v4
-        id: checkout
-        with:
-          fetch-depth: 0
-          submodules: true
-      - uses: actions/setup-python@v4
-        with:
-          python-version: '3.10'
-      - name: Install Ninja
-        if: matrix.os == 'windows-latest'
-        id: install_ninja
+          set -e
+          # Extract the tag name from GITHUB_REF
+          FULL_TAG=${GITHUB_REF#refs/tags/}
+          echo "Full tag: $FULL_TAG"
+          # Remove the 'python/' prefix
+          STRIPPED_TAG=${FULL_TAG#python/}
+          echo "Stripped tag: $STRIPPED_TAG"
+          # Set the output variable
+          echo "ref-tag=$STRIPPED_TAG" >> $GITHUB_OUTPUT
+
+      - name: Get Tag From Input
+        id: tag-input
+        if: github.event_name == 'workflow_dispatch'
+        shell: bash
         run: |
-          choco install ninja
-      - name: Set Mac flags
-        if: matrix.os == 'macos-latest' || matrix.os == 'macos-14'
+          set -e
+          FULL_TAG=${{ github.event.inputs.tag }}
+          echo "Full tag: $FULL_TAG"
+          # Remove the 'python/' prefix
+          STRIPPED_TAG=${FULL_TAG#python/}
+          echo "Stripped tag: $STRIPPED_TAG"
+
+          # Validate the tag format
+          if ! [[ $STRIPPED_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+|-beta[0-9]+|-alpha[0-9]+)?$ ]]; then
+            echo "Error: Invalid tag format. Expected format: 1.2.3, 1.2.3-rc1, 1.2.3-beta1, or 1.2.3-alpha1 but got: $STRIPPED_TAG"
+            exit 1
+          fi
+
+          # Set the output variable
+          echo "input-tag=$STRIPPED_TAG" >> $GITHUB_OUTPUT
+
+
+      - name: Output tag
+        id: tag-output
         run: |
-          echo "CMAKE_FLAGS=-DGGML_METAL_EMBED_LIBRARY=ON" >> $GITHUB_ENV
-      - name: Set Windows Env
-        if: matrix.os == 'windows-latest'
-        run: |
-          echo "SHARED_LIB_PATH=../../build/Release" >> $GITHUB_ENV
-      - name: Build wheels
-        run: |
-          make python-cidist
-        env:
-          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.8"
-          CIBW_BUILD: "cp${{matrix.python}}-*"
-          CIBW_SKIP: "pp* *musllinux*"
-          CIBW_ARCHS_MACOS: "arm64 x86_64"
-          CIBW_ARCHS_WINDOWS: "AMD64"
-          CIBW_ARCHS_LINUX: "x86_64 aarch64"
-          CIBW_BEFORE_BUILD: "make lib"
-          CIBW_TEST_REQUIRES: "pytest>=6.0.0 huggingface_hub"
-          CIBW_TEST_COMMAND: "python -m pytest {project}/bindings/python/tests/test"
-          CIBW_TEST_SKIP: "*-macosx_x86_64"
-      - name: Upload artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: python-package-distributions-${{matrix.os}}-${{matrix.python}}
-          path: dist
+          if [ "${{ github.event_name }}" == "push" ]; then
+            TAG=${{ steps.tag-ref.outputs.ref-tag }}
+            RELEASE_TAG=${GITHUB_REF#refs/tags/}
+          else
+            TAG=${{ steps.tag-input.outputs.input-tag }}
+            RELEASE_TAG=${{ github.event.inputs.tag }}
+          fi
+          echo "Tag: $TAG"
+          echo "tag=$TAG" >> $GITHUB_OUTPUT
+          echo "release-tag=$RELEASE_TAG" >> $GITHUB_OUTPUT
+        shell: bash
 
   upload:
     runs-on: ubuntu-latest
-    needs: build
+    needs: [py-test, tag-job]
     steps:
     - uses: actions/checkout@v4
       id: checkout
       with:
         fetch-depth: 0
         submodules: true
+
     - uses: actions/setup-python@v4
       with:
         python-version: "3.10"
-#    - name: Build sdist
-#      run: |
-#        make dist
+
+    - name: Update version
+      run: |
+        sed -i "s/^version = .*/version = \"${{ needs.tag-job.outputs.tag }}\"/" pyproject.toml
+        
+        # Check if the replacement was successful
+        if grep -q "version = \"${{ needs.tag-job.outputs.tag }}\"" pyproject.toml; then
+          echo "Successfully updated version to ${{ needs.tag-job.outputs.tag }} in pyproject.toml"
+        else
+          echo "Failed to update version in pyproject.toml"
+          exit 1
+        fi
+
     - name: Download wheels
       uses: actions/download-artifact@v4
       with:
         pattern: python-package-distributions*
         merge-multiple: true
         path: dist/
+
     - name: Create Source Distribution
       run: |
           pip install build
           make python-sdist
+
     - name: Publish to Test PyPI
       if: github.event.inputs.create_test_release == 'true'
       uses: pypa/gh-action-pypi-publish@release/v1
       with:
         password: ${{ secrets.TEST_PYPI_API_TOKEN }}
         repository-url: https://test.pypi.org/legacy/
+
     - name: Publish to PyPI
-      if: github.event.inputs.create_test_release != 'true'
+      if: github.event.inputs.create_release == 'true'
       uses: pypa/gh-action-pypi-publish@release/v1
       with:
         password: ${{ secrets.PYPI_API_TOKEN }}
+
+    - name: Commit and push updated pyproject.toml
+      if: github.event.event_name == 'push' #only commit and push on push events
+      run: |
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add pyproject.toml
+        git commit -m "Update version in pyproject.toml [skip ci]"
+        git push
